-- =============================================================================
-- PROYECTO: Raíces Criollas - Microservicio de Reservas
-- ARCHIVO: 02_esquema_reservas.sql
-- DESCRIPCIÓN: Definición del esquema DDL de 'reservas_db'
-- =============================================================================
-- INSTRUCCIONES PARA PGADMIN 4:
-- 1. En el panel izquierdo de pgAdmin 4, despliegue el árbol hasta 'Databases'.
-- 2. Haga clic derecho sobre 'reservas_db' y seleccione 'Query Tool'.
-- 3. Verifique en la barra superior que la conexión activa indique:
--    <servidor>/reservas_db@<usuario>
-- 4. Pegue y ejecute este script completo (F5 o botón de 'Play').
--
-- REGLAS ARQUITECTÓNICAS:
-- - Base de datos completamente desacoplada de 'auth_db' y 'menu_db'.
-- - El campo 'cliente_id' almacena el ID del usuario emitido en el claim 'sub'
--   del token JWT. NO se define clave foránea hacia la tabla de usuarios de Auth
--   porque pertenecen a bases de datos y microservicios independientes.
-- - No contiene sentencias DROP destructivas.
-- =============================================================================

-- =============================================================================
-- 1. TABLA: mesas
-- Corresponde a: com.raicescriollas.reservas.entity.Mesa
-- =============================================================================
CREATE TABLE IF NOT EXISTS mesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_mesa VARCHAR(50) NOT NULL,
    capacidad INTEGER NOT NULL,
    ubicacion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    -- Clave Primaria
    CONSTRAINT pk_mesas PRIMARY KEY (id),

    -- Restricción de unicidad para el número o código de mesa
    CONSTRAINT uk_mesas_numero_mesa UNIQUE (numero_mesa),

    -- Restricción de capacidad positiva
    CONSTRAINT chk_mesas_capacidad_positiva CHECK (capacidad > 0)
);

COMMENT ON TABLE mesas IS 'Catálogo de mesas físicas del restaurante para el módulo de reservas';
COMMENT ON COLUMN mesas.id IS 'Identificador único de la mesa (Generado por identidad autoincremental)';
COMMENT ON COLUMN mesas.numero_mesa IS 'Código o número único de la mesa (ej. M-01, VIP-1)';
COMMENT ON COLUMN mesas.capacidad IS 'Capacidad máxima de comensales sentados en la mesa';
COMMENT ON COLUMN mesas.ubicacion IS 'Descripción física o sector de la mesa (ej. Terraza, Salón Principal, Ventana)';
COMMENT ON COLUMN mesas.activo IS 'Estado operativo de la mesa (TRUE = Habilitada, FALSE = Fuera de servicio)';

-- =============================================================================
-- 2. TABLA: reservas
-- Corresponde a: com.raicescriollas.reservas.entity.Reserva
-- =============================================================================
CREATE TABLE IF NOT EXISTS reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id BIGINT NOT NULL,
    mesa_id BIGINT NOT NULL,
    fecha_inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    fecha_fin TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    cantidad_personas INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    observaciones VARCHAR(500),
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE,

    -- Clave Primaria
    CONSTRAINT pk_reservas PRIMARY KEY (id),

    -- Clave Foránea interna hacia mesas
    CONSTRAINT fk_reservas_mesa 
        FOREIGN KEY (mesa_id) 
        REFERENCES mesas (id) 
        ON DELETE RESTRICT 
        ON UPDATE CASCADE,

    -- Restricciones de integridad y validaciones de negocio
    CONSTRAINT chk_reservas_cantidad_personas CHECK (cantidad_personas > 0),
    CONSTRAINT chk_reservas_fechas_coherentes CHECK (fecha_inicio < fecha_fin),
    CONSTRAINT chk_reservas_estado_valido CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA'))
);

COMMENT ON TABLE reservas IS 'Registro de reservas de mesas efectuadas por clientes';
COMMENT ON COLUMN reservas.id IS 'Identificador único de la reserva';
COMMENT ON COLUMN reservas.cliente_id IS 'ID numérico del cliente obtenido del claim "sub" del JWT de autenticación';
COMMENT ON COLUMN reservas.mesa_id IS 'Referencia a la mesa reservada';
COMMENT ON COLUMN reservas.fecha_inicio IS 'Fecha y hora pactada para el inicio de la reserva';
COMMENT ON COLUMN reservas.fecha_fin IS 'Fecha y hora de finalización del intervalo reservado';
COMMENT ON COLUMN reservas.cantidad_personas IS 'Número de comensales para los que se reserva la mesa';
COMMENT ON COLUMN reservas.estado IS 'Estado actual: PENDIENTE, CONFIRMADA, CANCELADA o COMPLETADA';
COMMENT ON COLUMN reservas.observaciones IS 'Notas adicionales del comensal o solicitudes especiales';
COMMENT ON COLUMN reservas.fecha_creacion IS 'Marca de tiempo en que se registró la reserva en el sistema';
COMMENT ON COLUMN reservas.fecha_actualizacion IS 'Marca de tiempo de la última modificación o cambio de estado';

-- =============================================================================
-- 3. ÍNDICES DE RENDIMIENTO
-- Optimizados para las consultas de Disponibilidad, Solapamientos e Historial
-- =============================================================================

-- Índice para acelerar la verificación de solapamiento de horarios y disponibilidad
CREATE INDEX IF NOT EXISTS idx_reservas_mesa_horario 
    ON reservas (mesa_id, estado, fecha_inicio, fecha_fin);

-- Índice para consulta rápida de historial del cliente ("mis-reservas")
CREATE INDEX IF NOT EXISTS idx_reservas_cliente_fecha 
    ON reservas (cliente_id, fecha_inicio DESC);

-- Índice para búsquedas administrativas y reportes por rango de fechas
CREATE INDEX IF NOT EXISTS idx_reservas_fecha_inicio 
    ON reservas (fecha_inicio);

-- Índice para filtrado de mesas activas por capacidad
CREATE INDEX IF NOT EXISTS idx_mesas_activo_capacidad 
    ON mesas (activo, capacidad);
